services:
  app:
    image: mominul/packhub:latest
    container_name: packhub_app
    depends_on:
      - mongodb
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.env:/app/.env
      - ./key.gpg:/app/key.gpg
      - ${PACKHUB_DOCKER_CERT_PEM}:/app/fullchain.pem
      - ${PACKHUB_DOCKER_KEY_PEM}:/app/privkey.pem

  mongodb:
    image: mongo:5.0.6
    container_name: packhub_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${PACKHUB_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${PACKHUB_DB_PASSWORD}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
