name: Linux Distribution Test Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0.6
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: pass

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and run server container
      run: |
        docker build -t server -f images/server-ci.Dockerfile .
        docker run -d --network host --name server-container server

    - name: Wait for server to start
      run: |
        until curl --output /dev/null --silent --fail http://localhost:3000; do
          echo 'Waiting for server...'
          sleep 5
        done

    - name: Build and run Ubuntu 23.04 container
      run: |
        docker build -t ubuntu23.04 -f images/ubuntu23.04.Dockerfile scripts/
        docker run --name ubuntu23.04-test --network host ubuntu23.04 || true
    
    - name: Build and run Fedora 38 container
      run: |
        docker build -t fedora38 -f images/fedora38.Dockerfile scripts/
        docker run --name fedora38-test --network host fedora38 || true

    - name: Build and run Ubuntu 23.04 container for checking multiple package support
      run: |
        docker build -t ubuntu23.04-multi -f images/ubuntu23.04-multi-package.Dockerfile scripts/
        docker run --name ubuntu23.04-multitest --network host ubuntu23.04-multi || true
    
    - name: Check server logs
      run: |
        docker logs server-container || true
    
    - name: Check client containers' statuses
      run: |
        if [ "$(docker inspect -f '{{.State.ExitCode}}' ubuntu23.04-test)" -ne 0 ]; then
          echo "Test on Ubuntu 23.04 failed"
          exit 1
        fi
      
        if [ "$(docker inspect -f '{{.State.ExitCode}}' fedora38-test)" -ne 0 ]; then
          echo "Test on Fedora 38 failed"
          exit 1
        fi

        if [ "$(docker inspect -f '{{.State.ExitCode}}' ubuntu23.04-multitest)" -ne 0 ]; then
          echo "Test on Ubuntu 23.04 for multiple package support failed"
          exit 1
        fi
